query getCarriers @context(scope: "private") {
  carriers {
    totalNodes
    nodes {
      id
      name
      isActive
      slaType
      freightTableProcessStatus
      freightTableValueError
    }
  }
}
